// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCplS5W-9nBgujtzFz1nzvCre2YcBUtzIQ',
    appId: '1:286431093243:web:727e24b01c8dc038d82b5e',
    messagingSenderId: '286431093243',
    projectId: 'capcat-auth',
    authDomain: 'capcat-auth.firebaseapp.com',
    storageBucket: 'capcat-auth.firebasestorage.app',
    measurementId: 'G-T2QBY1F1HP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOag4cKWAPX_KX2XzEbnf2bAtG9MoUJ0Q',
    appId: '1:286431093243:android:965fffe9adcea7f1d82b5e',
    messagingSenderId: '286431093243',
    projectId: 'capcat-auth',
    storageBucket: 'capcat-auth.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBK8SUVflXxK1Xhe_uPiNyCcQSEUcUND10',
    appId: '1:286431093243:ios:4ad764bffe3cfa26d82b5e',
    messagingSenderId: '286431093243',
    projectId: 'capcat-auth',
    storageBucket: 'capcat-auth.firebasestorage.app',
    androidClientId: '286431093243-7dvia1rrfddgt3i807aum6sci8ss9bkc.apps.googleusercontent.com',
    iosClientId: '286431093243-7f0e5d86nk0476hb6rur54bltg6ttri8.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterChatMockApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBK8SUVflXxK1Xhe_uPiNyCcQSEUcUND10',
    appId: '1:286431093243:ios:4ad764bffe3cfa26d82b5e',
    messagingSenderId: '286431093243',
    projectId: 'capcat-auth',
    storageBucket: 'capcat-auth.firebasestorage.app',
    androidClientId: '286431093243-7dvia1rrfddgt3i807aum6sci8ss9bkc.apps.googleusercontent.com',
    iosClientId: '286431093243-7f0e5d86nk0476hb6rur54bltg6ttri8.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterChatMockApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCplS5W-9nBgujtzFz1nzvCre2YcBUtzIQ',
    appId: '1:286431093243:web:11b5b0562ddfc581d82b5e',
    messagingSenderId: '286431093243',
    projectId: 'capcat-auth',
    authDomain: 'capcat-auth.firebaseapp.com',
    storageBucket: 'capcat-auth.firebasestorage.app',
    measurementId: 'G-77FFG8TLZ2',
  );
}
